# Site settings
title: Mi Generacion
email: asapper@hotmail.com
description: Blog de temas relevantes para esta generación.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asapper.github.io" # the base hostname & protocol for your site
github_username: asapper

# Build settings
markdown: redcarpet
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Andy Sapper
