# Site settings
title: Mi Generacion
email: asapper@hotmail.com
description: Blog de temas relevantes para esta generación.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asapper.github.io" # the base hostname & protocol for your site
github_username: asapper
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: Andy Sapper
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      layout: "post"
      author: Andy Sapper
